### ISSUE TITLE
Harden security

### ISSUE THREAD

**Issue by levymetal** [nszeitli/CatanScoreboard#1]
Just in case the URL is discovered by a malicious party, we should harden the setup to prevent loss of data.

A few easy wins:

 - Disable signup (we can create new users manually when required)
 - Prevent unauthenticated users from editing/deleting games (still allow them to add though)

**Comment by nszeitli** [comment]
Dear levymetal,

Thank you for your concern. I have made the following changes:

- Signup still public (this shit be set and forget yo)
- Signup required to add games (track who added what)
- Admin role added manually to existing accounts
- Admin role required to edit any data
